### ISSUE TITLE
New suggestion for some of the keywords

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/queenbee#106]
@MingboPeng and @chriswmackey had a number of suggestions to improve the choice of words:

- Use `needs` instead of `dependencies` in tasks so it doesn't get confused with dependencies for operator dependencies.
- Change `arguments` to `with`. Similar to GitHub
- Change `outputs` to `returns`. Same logic as the first item.

This change will be a breaking change!

**Comment by mostaphaRoudsari** [comment]
Change the name for `operator` to `plugin`

**Comment by mostaphaRoudsari** [comment]
`Integration` might also be a good alternative for `operator` -> https://n8n.io/

**Comment by MingboPeng** [comment]
Why not just "plugin"?

**Comment by mostaphaRoudsari** [comment]
I'm concerned that people confuse them with the plugins for CAD tools. That's why I was thinking to use `extension` or `integration` but I see that everyone is fine with `plugin` - so I should be fine too! :)

**Comment by mostaphaRoudsari** [comment]
Implemented in io-refactor branch. Will close once the branch is merged.
