### ISSUE TITLE
Create workflow tracking schema primitives

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/queenbee#14]
Defining a workflow is great and all but we also want to be able to track/debug it. Queenbee should provide it's own primitives for tracking/debugging workflows so that each plugin can then report back the status of tasks in a unified manner.

**Comment by mostaphaRoudsari** [comment]
Tracking the workflows is part of whatever library that executes them. Queenbee is a workflow language and not an executor. That will be part of workerbee, queenbee-argo, etc.

**Comment by AntoineDao** [comment]
I agree that tracking should be performed by whichever plugin is actually running the DAG. My point above is about providing common primitive dataclasses to express them as. This way if someone goes from local to argo they can use the same tools to debug/understand what's up.
