### ISSUE TITLE
ProjectFolderSource is not generated properly for serialization in dotnet

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/queenbee#145]
For some reason, **ProjectFolderSource** class is generated without a construction with JsonConstructorAttribute, which is used for serialization. 
Here is an example for what should be:
![image](https://user-images.githubusercontent.com/9031066/93914411-843bcf80-fcd4-11ea-85f5-3235898f0cdc.png)

I guess we need to look into the different in between two OpenAPI or Pydantic objs

**Comment by mostaphaRoudsari** [comment]
I believe this has been resolved already. @MingboPeng, feel free to reopen the issue otherwise.
