### ISSUE TITLE
Generate "type" key for objects based on class name

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/queenbee#151]
When generating JSON/OpenAPI Schemas for dotnet the "type" key of certain objects should equal the model (class) name. We should probably automatically generate "type" keys from class names in the pydantic `BaseModel`  class.

**Comment by mostaphaRoudsari** [comment]
Actually now that I think about it we can add a validator to do that!

**Comment by mostaphaRoudsari** [comment]
The idea of using a `validator` to assign the type will not work as we need it to work. The type that is generated from the validators will not be included in the OpenAPI specification.

**Comment by mostaphaRoudsari** [comment]
Not exactly what was described here but it is implemented in `io-refactor` branch.

**Comment by AntoineDao** [comment]
Yeah I had a look at trying to implement some clever `type = cls.__name__` but it's actually quite tricky to do so for pydantic models as they get initialized in weird ways.
