### ISSUE TITLE
Recipe owner for local recipe

### ISSUE THREAD

**Issue by MingboPeng** [ladybug-tools/queenbee#173]
The local recipe object doesn't have owner key.
Do we want to use maintainer's info for displaying owner on UI?

cc @mostaphaRoudsari

**Comment by mostaphaRoudsari** [comment]
Good question. I'm not sure about the best approach. Let me think about it.

@AntoineDao, what do you think?

**Comment by AntoineDao** [comment]
This is a tricky one. I would tend to think that the local package repository on your machine is the `owner` of the Recipe and that the maintainers is a non-mandatory field that I would only use for enhancing information about the recipe.

In general I would think of an `owner` as a Pollination only concept. If you want to translate the concept of "the entity that contains a bunch of recipes I want to list from" then I would consider using the word `registry`. In that sense the folder on your local machine containing all the recipes you want is a `registry` in the same way that [`https://api.staging.pollination.cloud/registries/ladybug-tools`](https://api.staging.pollination.cloud/registries/ladybug-tools/index.json) is the url to a `registry` named `ladybug-tools`.

^ Not sure how much what I'm saying above makes sense. Do let me know if you think this warrants a quick call to clarify 😀

**Comment by mostaphaRoudsari** [comment]
closing this issue for now. we are not going to use a local repository.
