### ISSUE TITLE
Make `id` field optional

### ISSUE THREAD

**Issue by AntoineDao** [ladybug-tools/queenbee#38]
The more I think about the ID field for workflows the less it makes sense to me. The `id` field seems to be something we would use as an attribute of a simulation or a workflow saved on pollination cloud. However it serves no purpose as part of the queenbee schema. Do we think it makes sense to remove it or am I ranting?

**Comment by mostaphaRoudsari** [comment]
I see your point but I think for the exact reasons that you discussed we need a field for 'id'.

I agree that we should remove the auto-generated value for id. It can be an optional input which can be overwritten when it is saved to a database or tagged and used locally.

**Comment by AntoineDao** [comment]
Actually yeah that makes sense. I'll change the name of the issue accordingly :smile:

**Comment by theo-armour** [comment]
I am not party to the essence of this discussion, so this may or may not be
relevant:

In building projects the data changes all the time. The only way to know
and verify that the chunk of data bits you are currently examining are the
same or not is by comparing universally unique identifiers.

**Comment by AntoineDao** [comment]
No longer relevant as the workflow object has been overhauled.
