### ISSUE TITLE
Support operator-based commands

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/queenbee#41]
## Introduction

This issue discusses a limitation of how commands are added to functions. The challenge is unique to Queenbee and the source of the issue is that even though we support the concept of an operator which is intended to run in a docker container we want to run the same command locally and outside the docker too.

## Examples

Here are two examples that we have already faced:

1. Docker images with entrypoint: It is very common that someone sets-up a docker image with a code for entrypoint. This will change the command from how it will be called locally.
2. OS specific differences: Radiance is a good example for this. When one runs the commands locally on Windows they are written slightly different from how they will be executed on Linux or inside an Ubuntu docker image. This will block us from converting the workflow to Windows and Linux successfully. 

## Possible solution

Add a new field for command_local with sub-fields for Windows, Mac and Linux. This field is optional and will only be used by extensions that support local execution. We can also have a queenbee command that generates a version of workflow to be used for local run on a system.

`queenbee translate <input workflow> <output workflow> --local [windows|mac|linux]`

cc: @AntoineDao

**Comment by AntoineDao** [comment]
Ah yes this does sound like a pickle. Providing some solution on Queenbee's side feels like a potential rabbit hole. We could offload to operator designers. Here's some quick-fixes I imagine could work:

### No `entrypoint.sh`

The use of entrypoints in Docker is mostly to add script options dynamically or configure specific behavior based on  env vars etc...

Here's an example of a common `entrypoint.sh`:

```bash
#!/usr/bin/env bash
set -e

if [ "$1" = 'postgres' ]; then
    chown -R postgres "$PGDATA"

    if [ -z "$(ls -A "$PGDATA")" ]; then
        gosu postgres initdb
    fi

    exec gosu postgres "$@"
fi

exec "$@"
```

### OS Agnostic Operators

Trying to handle os specific differences in Queenbee seems inapropriate as Queenbee does not have any knowledge of the operator implementation (ie: radiance). As such I reckon we would be better off enforcing "os agnostic" operator commands.

In the case of radiance I would propose implementing this through a python wrapper.

**Comment by mostaphaRoudsari** [comment]
Not sure if I follow your suggestion. From the same page that you have copied the sample you can see more examples of how they are used for setting up the default command.

https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#entrypoint

> In the case of radiance I would propose implementing this through a python wrapper.

This is a lot of work and basically what we did in honeybee commands for Radiance: (https://github.com/ladybug-tools/honeybee/tree/master/honeybee/radiance/command). We can go back in that direction but I was hoping to offload that to the workflow not the other way around. 😀

**Comment by AntoineDao** [comment]
### Entrypoint

Yes the entrypoint can also be used to set the default command and use the `CMD` and `ARGS` to set other command line values. I think it would be acceptable to just say `this is not allowed` and every function template should contain the entire command line string for an executable.

### OS Agnostic operators

Maybe worth having a call to hash this out properly at some point to see what the better way forward is. I see the benefit of handling it on Queenbee's side to make things easier for operator builders, however I think we both agree this has the potential to be an immense rabbit hole.

**Comment by AntoineDao** [comment]
Another bit of fun to consider which will cause issues with Queenbee workflows or Operators is that if we consider using Windows Containers (in the medium/long term) we will have to support fun new file paths for artifacts.

Currently an Operator **must** set it's working directory to `opt/run-folder/` as a convention so Argo knows where to upload/download artifacts in the container.

https://github.com/ladybug-tools/honeybee-radiance/blob/dc9960a3e29663ed1d55b9ebf430bdad0dadd228/Dockerfile#L1-L16

Windows containers however set their directory according to windows directory semantics as shown in [these docs](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/manage-windows-dockerfile#workdir).

This means we'll probably have to introduce an Operator OS flag on it somewhere to handle this downstream.

**Comment by mostaphaRoudsari** [comment]
> Windows containers however set their directory according to windows directory semantics as shown in these docs.

I think Windows can handle unix like path too. The documentation says in case you use \ then make sure to escape it \\.

> This means we'll probably have to introduce an Operator OS flag on it somewhere to handle this downstream.

Yes. We have to do this anyways for running the workflows locally. The question is if we want to get smart about it or we offload that to the user but giving them the option to provide OS specific inputs where needed.

> Maybe worth having a call to hash this out properly at some point to see what the better way forward is.

👍

**Comment by mostaphaRoudsari** [comment]
We decided that the complexity should be handled inside the function command itself. I'm closing this for now until later.
