### ISSUE TITLE
Remove argo and pollination plugins from command line help

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/queenbee#55]
I personally think they should only show up in the help if one has them installed not the other way around.

![image](https://user-images.githubusercontent.com/2915573/82266261-3c2c2b00-9937-11ea-9dc4-3ebf87b9fa0b.png)

**Comment by mostaphaRoudsari** [comment]
cc @AntoineDao!

**Comment by AntoineDao** [comment]
That's how they work yes. You need to uninstall them from your machine for queenbee to stop picking them up.
