### ISSUE TITLE
Redoc recipe documentation doesn't render correctly

### ISSUE THREAD

**Issue by mostaphaRoudsari** [ladybug-tools/queenbee#58]
http://localhost:8000/_static/redoc-recipe.html

![image](https://user-images.githubusercontent.com/2915573/82269903-0be98a00-9941-11ea-898e-5f41f1d267db.png)

For some reason the schema is generated twice inside the JSON file.

**Comment by AntoineDao** [comment]
Your PR solved this issue. Good catch thanks!
